AWSTemplateFormatVersion: "2010-09-09"
Description: |
  CloudFormation Template for Nagios on EC2.
Parameters:
  NagiosPassword:
    AllowedPattern: '^[A-Za-z][a-zA-Z0-9@%$_-]{8,41}$'
    ConstraintDescription: must contain only alphanumeric characters.
    Description: The WordPress database admin account password
    MaxLength: '41'
    MinLength: '8'
    Default: 'nagiosadmin'
    Type: String
  Email:
    Description: The WordPress database admin account password
    MaxLength: '41'
    MinLength: '8'
    Default: 'drmehmet510@gmail.com'
    Type: String 
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.small
      - t2.micro
      - m1.small
      - m1.medium
      - m1.large
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  RegionImageMap:
    us-east-1:
      AMI: ami-0c94855ba95c71c99
    us-east-2:
      AMI: ami-0603cbe34fd08cb81
    us-west-1:
      AMI: ami-0e65ed16c9bf1abc7
    us-west-2:
      AMI: ami-0841edc20334f9287
    eu-west-1:
      AMI: ami-08a2aed6e0a6f9c7d
Resources:
  NagiosSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'Nagios Access Security Group'
      GroupDescription: 'Nagios Access Security Group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '5666'
          ToPort: '5666'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: icmp
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: RulesInbound
  NagiosXI:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: nagios-cf
      UserData:
        Fn::Base64: 
          !Sub 
            - |
              #!/bin/bash
              #disable selinux
              sudo sed -i 's/enforcing/disabled/g' /etc/selinux/config
              #config hostname
              hostname nagios
              echo "nagios" >/etc/hostname
              amazon-linux-extras install epel -y
              yum install httpd php gcc glibc glibc-common gd gd-devel openssl-devel make net-snmp -y
              systemctl start httpd
              systemctl enable httpd 
              yum install wget -y
              adduser -m nagios
              echo ${NagiosPassword} | passwd nagios --stdin
              groupadd nagcmd
              usermod -a -G nagcmd nagios
              usermod -a -G nagcmd apache
              mkdir -p /home/ec2-user/nagios && cd /home/ec2-user/nagios
              wget http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.0.8.tar.gz
              wget http://nagios-plugins.org/download/nagios-plugins-2.0.3.tar.gz
              tar zxvf nagios-4.0.8.tar.gz
              cd /home/ec2-user/nagios/nagios-4.0.8 &&  ./configure --with-command-group=nagcmd
              make all
              make install
              make install-init
              make install-config
              make install-commandmode
              sed -i 's|nagios@localhost|${Email}|g' /usr/local/nagios/etc/objects/contacts.cfg
              make install-webconf
              htpasswd -b -c /usr/local/nagios/etc/htpasswd.users nagiosadmin ${NagiosPassword}
              service httpd restart
              cd /home/ec2-user/nagios && tar zxvf nagios-plugins-2.0.3.tar.gz 
              cd /home/ec2-user/nagios/nagios-plugins-2.0.3 && ./configure --with-nagios-user=nagios --with-nagios-group=nagios
              make && make install
              chkconfig --add nagios
              chkconfig nagios on
              service nagios start

              #Nrpe-check
              cd /home/ec2-user/nagios
              wget https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-4.0.2/nrpe-4.0.2.tar.gz
              tar xzf nrpe-4.0.2.tar.gz && cd /home/ec2-user/nagios/nrpe-4.0.2 && ./configure
              make all && make install-plugin && su
              cat >>/usr/local/nagios/etc/objects/commands.cfg<<EOF
              #########################################################
              #NRPE CHECK
              ########################################################

              # 'check_nrpe' command definition
              define command{
              command_name check_nrpe
              command_line $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
                      }
              EOF

              #Host ve Servis Grup Tanımlamaları
              cd /usr/local/nagios/etc/objects/
              cat >>/usr/local/nagios/etc/objects/templates.cfg<<EOF
              ###############################################################################
              ###############################################################################
              #
              # HOST/SERVICE GROUP DEFINITIONS
              #
              ###############################################################################
              ###############################################################################

              define hostgroup{
                      hostgroup_name  windows-servers ; Host Grubunun Adi
                      alias           Windows Servers ; Aciklama
                      members         WIN2003  ; Gruba uye makineler.
                      }

              define hostgroup{
                      hostgroup_name  linux-servers ; Host Grubunun Adi
                      alias           *Nix Servers ; Aciklama
                      members         localhost,CENTOS ; Gruba uye makineler
                      }

              define servicegroup{
                      servicegroup_name       CPU
                      alias                   Islemci Durumu
                      }

              define servicegroup{
                      servicegroup_name       Memory
                      alias                   Ram Durumu
                      }

              define servicegroup{
                      servicegroup_name       DISK
                      alias                   DISK Durumu
                      }

              define servicegroup{
                      servicegroup_name       HTTP
                      alias                   Web Server Durumu
                      }

              define servicegroup{
                      servicegroup_name       SMTP
                      alias                   Mail Server Durumu
                      }

              define servicegroup{
                      servicegroup_name       FTP
                      alias                   FTP Server Durumu
                      }
              EOF
              
              #localhost.cfg ve windows.cfg dosyalarından # HOSTGROUP DEFINITIONS bölümlerini silmeniz gerekiyor.
              touch /usr/local/nagios/etc/objects/centos.cfg
              touch /usr/local/nagios/etc/objects/win2003.cfg

              cat >>/usr/local/nagios/etc/objects/centos.cfg<<EOF
              #####################################################################
              #
              #CENTOS HOST DEFINITIONS
              #
              #####################################################################
              define host{
                      use linux-server
                      host_name CENTOS
                      alias  CENTOS / CentOS 5.2 64bit
                      address ${NAGİOSHOST}
              }

              define service{
                      use generic-service
                      host_name CENTOS
                      service_description CPU Load
                      servicegroups   CPU
                      check_command check_nrpe!check_load
                      }

              define service{
                      use generic-service
                      host_name CENTOS
                      service_description Current Users

                      check_command check_nrpe!check_users
                      }

              define service{
                      use  generic-service
                      host_name CENTOS
                      service_description / Free Space
                      servicegroups   DISK
                      check_command check_nrpe!check_disk
                      }

              define service{
                      use generic-service
                      host_name CENTOS
                      service_description Total Processes
                      check_command check_nrpe!check_total_procs
                      }

              define service{
                      use generic-service
                      host_name CENTOS
                      service_description Zombie Processes
                      check_command check_nrpe!check_zombie_procs
                      }
              EOF
              cat >>/usr/local/nagios/etc/objects/win2003.cfg<<EOF
              #####################################################################
              #
              #WINDOWS HOST YAPILANDIRMA DOSYASI
              #####################################################################
              define host{
                      use             windows-server
                      host_name       WIN2003
                      alias           WIN2003 - Windows 2003
                      address         192.168.1.13
                      }

              define service{
                      use                     generic-service
                      host_name               WIN2003
                      service_description     NSClient++ Version
                      check_command           check_nt!CLIENTVERSION
                      }

              define service{
                      use                     generic-service
                      host_name               WIN2003
                      service_description     Uptime
                      check_command           check_nt!UPTIME
                      }

              define service{
                      use                     generic-service
                      host_name               WIN2003
                      service_description     CPU Load
                      servicegroups           CPU
                      check_command           check_nt!CPULOAD!-l 5,80,90
                      }

              define service{
                      use                     generic-service
                      host_name               WIN2003
                      service_description     Memory Usage
                      servicegroups           Memory
                      check_command           check_nt!MEMUSE!-w 80 -c 90
                      }

              define service{
                      use                     generic-service
                      host_name               WIN2003
                      service_description     C:\ Drive Space
                      servicegroups           DISK
                      check_command           check_nt!USEDDISKSPACE!-l c -w 80 -c 90
                      }

              define service{
                      use                     generic-service
                      host_name               WIN2003
                      service_description     D:\ Drive Space
                      servicegroups           DISK
                      check_command           check_nt!USEDDISKSPACE!-l d -w 90 -c 95
                      }
              EOF
              sed -i '36icfg_file=/usr/local/nagios/etc/objects/centos.cfg' /usr/local/nagios/etc/nagios.cfg
              sed -i '39icfg_file=/usr/local/nagios/etc/objects/centos.cfg' /usr/local/nagios/etc/nagios.cfg
            - NAGİOSHOST: !GetAtt NagiosHostRedhat.PublicIp

      KeyName: !Ref KeyName
      ImageId: !FindInMap 
        - RegionImageMap
        - !Ref AWS::Region
        - AMI
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !GetAtt NagiosSecurityGroup.GroupId

  NagiosHostRedhat:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: nagios-host-linux
      UserData:
        Fn::Base64: 
          !Sub 
            - |
              #!/bin/bash
              yum update -y
              yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
              yum -y install nagios-nrpe
              chkconfig --level 2345 nrpe on
              sed -i '/allowed_hosts=127.0.0.1,::1,/s/$/${NAGİOSSERVER}/' /etc/nagios/nrpe.cfg
              service nrpe start
              dnf install net-tools
            - NAGİOSSERVER: !GetAtt NagiosXI.PublicIp
      KeyName: !Ref KeyName  #netstat -an |grep 5666
      ImageId: ami-0b0af3577fe5e3532
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !GetAtt NagiosSecurityGroup.GroupId
 
Outputs:
  IPNagiosXI:
    Description: Nagios XI IP
    Value: !Join [ "", [ 'http://',!GetAtt NagiosXI.PublicIp, '/nagios/' ]]
